---
- name: Enable and start system-level systemd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ (system_services | default([], true)) + (system_services_extra | default([], true)) }}"
